[package]
name = "brume"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
base64 = "0.22.1"
bytes = "1.11.1"
rust-crypto = "0.2.36"
serde = { version = "^1", features = ["derive"] }
serde_json = "1.0"
tokio = "^1.44"
