[package]
name = "brume"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
bytes = "1.11.1"
serde = { version = "^1", features = ["derive"] }
serde_json = "1.0"
tokio = "^1.44"
